<?php
/**
 * Gravitation Shop States: Indonesia Provinces
 *
 * @author 		UlisesFreitas
 * @category 	Core
 * @package 	Gravitation Shop/Library
 * @version 	1.0.0
 */


if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

global $states;

$states['IT'] = array(
	'AG'    => __( 'Agrigento', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'AL' => __( 'Alessandria', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'AN' => __( 'Ancona', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'AO' => __( 'Aosta', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'AR' => __( 'Arezzo', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'AP' => __( 'Ascoli Piceno', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'AT' => __( 'Asti', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'AV' => __( 'Avellino', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'BA' => __( 'Bari', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'BT' => __( 'Barletta-Andria-Trani', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'BL' => __( 'Belluno', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'BN' => __( 'Benevento', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'BG' => __( 'Bergamo', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'BI' => __( 'Biella', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'BO' => __( 'Bologna', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'BZ' => __( 'Bolzano', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'BS' => __( 'Brescia', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'BR' => __( 'Brindisi', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'CA' => __( 'Cagliari', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'CL' => __( 'Caltanissetta', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'CB' => __( 'Campobasso', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'CI' => __( 'Carbonia-Iglesias', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'CE' => __( 'Caserta', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'CT' => __( 'Catania', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'CZ' => __( 'Catanzaro', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'CH' => __( 'Chieti', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'CO' => __( 'Como', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'CS' => __( 'Cosenza', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'CR' => __( 'Cremona', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'KR' => __( 'Crotone', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'CN' => __( 'Cuneo', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'EN' => __( 'Enna', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'FM' => __( 'Fermo', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'FE' => __( 'Ferrara', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'FI' => __( 'Firenze', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'FG' => __( 'Foggia', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'FC' => __( 'Forlì-Cesena', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'FR' => __( 'Frosinone', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'GE' => __( 'Genova', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'GO' => __( 'Gorizia', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'GR' => __( 'Grosseto', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'IM' => __( 'Imperia', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'IS' => __( 'Isernia', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'SP' => __( 'La Spezia', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'AQ' => __( 'L&apos;Aquila', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'LT' => __( 'Latina', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'LE' => __( 'Lecce', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'LC' => __( 'Lecco', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'LI' => __( 'Livorno', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'LO' => __( 'Lodi', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'LU' => __( 'Lucca', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'MC' => __( 'Macerata', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'MN' => __( 'Mantova', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'MS' => __( 'Massa-Carrara', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'MT' => __( 'Matera', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'ME' => __( 'Messina', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'MI' => __( 'Milano', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'MO' => __( 'Modena', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'MB' => __( 'Monza e della Brianza', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'NA' => __( 'Napoli', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'NO' => __( 'Novara', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'NU' => __( 'Nuoro', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'OT' => __( 'Olbia-Tempio', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'OR' => __( 'Oristano', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PD' => __( 'Padova', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PA' => __( 'Palermo', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PR' => __( 'Parma', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PV' => __( 'Pavia', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PG' => __( 'Perugia', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PU' => __( 'Pesaro e Urbino', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PE' => __( 'Pescara', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PC' => __( 'Piacenza', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PI' => __( 'Pisa', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PT' => __( 'Pistoia', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PN' => __( 'Pordenone', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PZ' => __( 'Potenza', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'PO' => __( 'Prato', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'RG' => __( 'Ragusa', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'RA' => __( 'Ravenna', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'RC' => __( 'Reggio Calabria', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'RE' => __( 'Reggio Emilia', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'RI' => __( 'Rieti', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'RN' => __( 'Rimini', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'RM' => __( 'Roma', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'RO' => __( 'Rovigo', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'SA' => __( 'Salerno', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'VS' => __( 'Medio Campidano', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'SS' => __( 'Sassari', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'SV' => __( 'Savona', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'SI' => __( 'Siena', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'SR' => __( 'Siracusa', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'SO' => __( 'Sondrio', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'TA' => __( 'Taranto', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'TE' => __( 'Teramo', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'TR' => __( 'Terni', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'TO' => __( 'Torino', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'OG' => __( 'Ogliastra', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'TP' => __( 'Trapani', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'TN' => __( 'Trento', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'TV' => __( 'Treviso', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'TS' => __( 'Trieste', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'UD' => __( 'Udine', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'VA' => __( 'Varese', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'VE' => __( 'Venezia', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'VB' => __( 'Verbano-Cusio-Ossola', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'VC' => __( 'Vercelli', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'VR' => __( 'Verona', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'VV' => __( 'Vibo Valentia', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'VI' => __( 'Vicenza', GRAVITATION_SHOP_TEXT_DOMAIN ),
    'VT' => __( 'Viterbo', GRAVITATION_SHOP_TEXT_DOMAIN )
);